# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.lbl_title.setStyleSheet("background-color: rgb(100, 178, 244);\n"
"font: 75 18pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lbl_title.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_back = QtWidgets.QLabel(self.centralwidget)
        self.lbl_back.setGeometry(QtCore.QRect(1, 1, 49, 49))
        self.lbl_back.setStyleSheet("image: url(:/icon/back_arrow.png);\n"
"background-color: rgba(79, 255, 144, 0);")
        self.lbl_back.setText("")
        self.lbl_back.setObjectName("lbl_back")
        self.lbl_edit = QtWidgets.QLabel(self.centralwidget)
        self.lbl_edit.setGeometry(QtCore.QRect(745, 1, 49, 49))
        self.lbl_edit.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/icon/keyboard.png);")
        self.lbl_edit.setText("")
        self.lbl_edit.setObjectName("lbl_edit")
        self.lbl_frame = QtWidgets.QLabel(self.centralwidget)
        self.lbl_frame.setGeometry(QtCore.QRect(5, 55, 790, 420))
        self.lbl_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_frame.setText("")
        self.lbl_frame.setObjectName("lbl_frame")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(750, 390, 49, 49))
        self.btn_next.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-image: url(:/icon/next.png);")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.text_equation = QtWidgets.QLineEdit(self.centralwidget)
        self.text_equation.setGeometry(QtCore.QRect(10, 230, 581, 221))
        self.text_equation.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 75 10pt \"Arial\";")
        self.text_equation.setText("")
        self.text_equation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_equation.setObjectName("text_equation")
        self.btn_op1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op1.setGeometry(QtCore.QRect(10, 60, 75, 75))
        self.btn_op1.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op1.PNG);")
        self.btn_op1.setText("")
        self.btn_op1.setObjectName("btn_op1")
        self.panel_op1 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op1.setEnabled(True)
        self.panel_op1.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op1.setObjectName("panel_op1")
        self.selection = QtWidgets.QLabel(self.panel_op1)
        self.selection.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection.setText("")
        self.selection.setObjectName("selection")
        self.btn_1_1 = QtWidgets.QPushButton(self.panel_op1)
        self.btn_1_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_1_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op1.PNG);")
        self.btn_1_1.setText("")
        self.btn_1_1.setObjectName("btn_1_1")
        self.btn_1_2 = QtWidgets.QPushButton(self.panel_op1)
        self.btn_1_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_1_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op1_2.PNG);")
        self.btn_1_2.setText("")
        self.btn_1_2.setObjectName("btn_1_2")
        self.btn_op2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op2.setGeometry(QtCore.QRect(90, 60, 75, 75))
        self.btn_op2.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op2.PNG);")
        self.btn_op2.setText("")
        self.btn_op2.setObjectName("btn_op2")
        self.btn_op3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op3.setGeometry(QtCore.QRect(170, 60, 75, 75))
        self.btn_op3.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op3.PNG);")
        self.btn_op3.setText("")
        self.btn_op3.setObjectName("btn_op3")
        self.btn_op4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op4.setGeometry(QtCore.QRect(250, 60, 75, 75))
        self.btn_op4.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op4.PNG);")
        self.btn_op4.setText("")
        self.btn_op4.setObjectName("btn_op4")
        self.btn_op5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op5.setGeometry(QtCore.QRect(330, 60, 75, 75))
        self.btn_op5.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op5.PNG);")
        self.btn_op5.setText("")
        self.btn_op5.setObjectName("btn_op5")
        self.btn_op6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op6.setGeometry(QtCore.QRect(410, 60, 75, 75))
        self.btn_op6.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op6.PNG);")
        self.btn_op6.setText("")
        self.btn_op6.setObjectName("btn_op6")
        self.btn_op7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op7.setGeometry(QtCore.QRect(490, 60, 75, 75))
        self.btn_op7.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op7.PNG);")
        self.btn_op7.setText("")
        self.btn_op7.setObjectName("btn_op7")
        self.btn_op8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op8.setGeometry(QtCore.QRect(10, 140, 75, 75))
        self.btn_op8.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op8.PNG);")
        self.btn_op8.setText("")
        self.btn_op8.setObjectName("btn_op8")
        self.btn_op9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op9.setGeometry(QtCore.QRect(90, 140, 75, 75))
        self.btn_op9.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op9.PNG);")
        self.btn_op9.setText("")
        self.btn_op9.setObjectName("btn_op9")
        self.btn_op10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op10.setGeometry(QtCore.QRect(170, 140, 75, 75))
        self.btn_op10.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op10.PNG);")
        self.btn_op10.setText("")
        self.btn_op10.setObjectName("btn_op10")
        self.btn_op11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_op11.setGeometry(QtCore.QRect(250, 140, 75, 75))
        self.btn_op11.setStyleSheet("background-color: rgba(250, 250, 250, 0);\n"
"image: url(:/op/op11.PNG);")
        self.btn_op11.setText("")
        self.btn_op11.setObjectName("btn_op11")
        self.panel_op2 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op2.setEnabled(True)
        self.panel_op2.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op2.setObjectName("panel_op2")
        self.selection_2 = QtWidgets.QLabel(self.panel_op2)
        self.selection_2.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_2.setText("")
        self.selection_2.setObjectName("selection_2")
        self.btn_2_1 = QtWidgets.QPushButton(self.panel_op2)
        self.btn_2_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_2_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op2.PNG);")
        self.btn_2_1.setText("")
        self.btn_2_1.setObjectName("btn_2_1")
        self.btn_2_2 = QtWidgets.QPushButton(self.panel_op2)
        self.btn_2_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_2_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op2_2.PNG);")
        self.btn_2_2.setText("")
        self.btn_2_2.setObjectName("btn_2_2")
        self.panel_op3 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op3.setEnabled(True)
        self.panel_op3.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op3.setObjectName("panel_op3")
        self.selection_4 = QtWidgets.QLabel(self.panel_op3)
        self.selection_4.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_4.setText("")
        self.selection_4.setObjectName("selection_4")
        self.btn_3_1 = QtWidgets.QPushButton(self.panel_op3)
        self.btn_3_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_3_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op3.PNG);")
        self.btn_3_1.setText("")
        self.btn_3_1.setObjectName("btn_3_1")
        self.panel_op4 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op4.setEnabled(True)
        self.panel_op4.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op4.setObjectName("panel_op4")
        self.selection_5 = QtWidgets.QLabel(self.panel_op4)
        self.selection_5.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_5.setText("")
        self.selection_5.setObjectName("selection_5")
        self.btn_4_1 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_4_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4.PNG);")
        self.btn_4_1.setText("")
        self.btn_4_1.setObjectName("btn_4_1")
        self.btn_4_2 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_4_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4_2.PNG);")
        self.btn_4_2.setText("")
        self.btn_4_2.setObjectName("btn_4_2")
        self.btn_4_3 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_4_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4_3.PNG);")
        self.btn_4_3.setText("")
        self.btn_4_3.setObjectName("btn_4_3")
        self.btn_4_4 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_4_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4_4.PNG);")
        self.btn_4_4.setText("")
        self.btn_4_4.setObjectName("btn_4_4")
        self.btn_4_5 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_5.setGeometry(QtCore.QRect(5, 120, 85, 50))
        self.btn_4_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4_5.PNG);")
        self.btn_4_5.setText("")
        self.btn_4_5.setObjectName("btn_4_5")
        self.btn_4_6 = QtWidgets.QPushButton(self.panel_op4)
        self.btn_4_6.setGeometry(QtCore.QRect(95, 120, 85, 50))
        self.btn_4_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op4_6.PNG);")
        self.btn_4_6.setText("")
        self.btn_4_6.setObjectName("btn_4_6")
        self.panel_op5 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op5.setEnabled(True)
        self.panel_op5.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op5.setObjectName("panel_op5")
        self.selection_7 = QtWidgets.QLabel(self.panel_op5)
        self.selection_7.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_7.setText("")
        self.selection_7.setObjectName("selection_7")
        self.btn_5_1 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_5_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5.PNG);")
        self.btn_5_1.setText("")
        self.btn_5_1.setObjectName("btn_5_1")
        self.btn_5_2 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_5_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5_2.PNG);")
        self.btn_5_2.setText("")
        self.btn_5_2.setObjectName("btn_5_2")
        self.btn_5_3 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_5_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5_3.PNG);")
        self.btn_5_3.setText("")
        self.btn_5_3.setObjectName("btn_5_3")
        self.btn_5_4 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_5_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5_4.PNG);")
        self.btn_5_4.setText("")
        self.btn_5_4.setObjectName("btn_5_4")
        self.btn_5_5 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_5.setGeometry(QtCore.QRect(5, 120, 85, 50))
        self.btn_5_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5_5.PNG);")
        self.btn_5_5.setText("")
        self.btn_5_5.setObjectName("btn_5_5")
        self.btn_5_6 = QtWidgets.QPushButton(self.panel_op5)
        self.btn_5_6.setGeometry(QtCore.QRect(95, 120, 85, 50))
        self.btn_5_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op5_6.PNG);")
        self.btn_5_6.setText("")
        self.btn_5_6.setObjectName("btn_5_6")
        self.panel_op6 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op6.setEnabled(True)
        self.panel_op6.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op6.setObjectName("panel_op6")
        self.selection_8 = QtWidgets.QLabel(self.panel_op6)
        self.selection_8.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_8.setText("")
        self.selection_8.setObjectName("selection_8")
        self.btn_6_1 = QtWidgets.QPushButton(self.panel_op6)
        self.btn_6_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_6_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op6.PNG);")
        self.btn_6_1.setText("")
        self.btn_6_1.setObjectName("btn_6_1")
        self.btn_6_2 = QtWidgets.QPushButton(self.panel_op6)
        self.btn_6_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_6_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op6_2.PNG);")
        self.btn_6_2.setText("")
        self.btn_6_2.setObjectName("btn_6_2")
        self.btn_6_3 = QtWidgets.QPushButton(self.panel_op6)
        self.btn_6_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_6_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op6_3.PNG);")
        self.btn_6_3.setText("")
        self.btn_6_3.setObjectName("btn_6_3")
        self.btn_6_4 = QtWidgets.QPushButton(self.panel_op6)
        self.btn_6_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_6_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op6_4.PNG);")
        self.btn_6_4.setText("")
        self.btn_6_4.setObjectName("btn_6_4")
        self.panel_op7 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op7.setEnabled(True)
        self.panel_op7.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op7.setObjectName("panel_op7")
        self.selection_10 = QtWidgets.QLabel(self.panel_op7)
        self.selection_10.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_10.setText("")
        self.selection_10.setObjectName("selection_10")
        self.btn_7_1 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_7_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7.PNG);")
        self.btn_7_1.setText("")
        self.btn_7_1.setObjectName("btn_7_1")
        self.btn_7_2 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_7_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_2.PNG);")
        self.btn_7_2.setText("")
        self.btn_7_2.setObjectName("btn_7_2")
        self.btn_7_3 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_7_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_3.PNG);")
        self.btn_7_3.setText("")
        self.btn_7_3.setObjectName("btn_7_3")
        self.btn_7_4 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_7_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_4.PNG);")
        self.btn_7_4.setText("")
        self.btn_7_4.setObjectName("btn_7_4")
        self.btn_7_5 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_5.setGeometry(QtCore.QRect(5, 115, 85, 50))
        self.btn_7_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_5.PNG);")
        self.btn_7_5.setText("")
        self.btn_7_5.setObjectName("btn_7_5")
        self.btn_7_6 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_6.setGeometry(QtCore.QRect(95, 115, 85, 50))
        self.btn_7_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_6.PNG);")
        self.btn_7_6.setText("")
        self.btn_7_6.setObjectName("btn_7_6")
        self.btn_7_7 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_7.setGeometry(QtCore.QRect(5, 170, 85, 50))
        self.btn_7_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_7.PNG);")
        self.btn_7_7.setText("")
        self.btn_7_7.setObjectName("btn_7_7")
        self.btn_7_8 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_8.setGeometry(QtCore.QRect(95, 170, 85, 50))
        self.btn_7_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_8.PNG);")
        self.btn_7_8.setText("")
        self.btn_7_8.setObjectName("btn_7_8")
        self.btn_7_9 = QtWidgets.QPushButton(self.panel_op7)
        self.btn_7_9.setGeometry(QtCore.QRect(5, 225, 85, 50))
        self.btn_7_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op7_9.PNG);")
        self.btn_7_9.setText("")
        self.btn_7_9.setObjectName("btn_7_9")
        self.panel_op8 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op8.setEnabled(True)
        self.panel_op8.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op8.setObjectName("panel_op8")
        self.selection_11 = QtWidgets.QLabel(self.panel_op8)
        self.selection_11.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_11.setText("")
        self.selection_11.setObjectName("selection_11")
        self.btn_8_1 = QtWidgets.QPushButton(self.panel_op8)
        self.btn_8_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_8_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op8.PNG);")
        self.btn_8_1.setText("")
        self.btn_8_1.setObjectName("btn_8_1")
        self.btn_8_2 = QtWidgets.QPushButton(self.panel_op8)
        self.btn_8_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_8_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op8_2.PNG);")
        self.btn_8_2.setText("")
        self.btn_8_2.setObjectName("btn_8_2")
        self.btn_8_3 = QtWidgets.QPushButton(self.panel_op8)
        self.btn_8_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_8_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op8_3.PNG);")
        self.btn_8_3.setText("")
        self.btn_8_3.setObjectName("btn_8_3")
        self.btn_8_4 = QtWidgets.QPushButton(self.panel_op8)
        self.btn_8_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_8_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op8_4.PNG);")
        self.btn_8_4.setText("")
        self.btn_8_4.setObjectName("btn_8_4")
        self.btn_8_5 = QtWidgets.QPushButton(self.panel_op8)
        self.btn_8_5.setGeometry(QtCore.QRect(5, 115, 85, 50))
        self.btn_8_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op8_5.PNG);")
        self.btn_8_5.setText("")
        self.btn_8_5.setObjectName("btn_8_5")
        self.panel_op9 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op9.setEnabled(True)
        self.panel_op9.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op9.setObjectName("panel_op9")
        self.selection_12 = QtWidgets.QLabel(self.panel_op9)
        self.selection_12.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_12.setText("")
        self.selection_12.setObjectName("selection_12")
        self.btn_9_1 = QtWidgets.QPushButton(self.panel_op9)
        self.btn_9_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_9_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op9.PNG);")
        self.btn_9_1.setText("")
        self.btn_9_1.setObjectName("btn_9_1")
        self.btn_9_2 = QtWidgets.QPushButton(self.panel_op9)
        self.btn_9_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_9_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op9_2.PNG);")
        self.btn_9_2.setText("")
        self.btn_9_2.setObjectName("btn_9_2")
        self.panel_op10 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op10.setEnabled(True)
        self.panel_op10.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op10.setObjectName("panel_op10")
        self.selection_13 = QtWidgets.QLabel(self.panel_op10)
        self.selection_13.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_13.setText("")
        self.selection_13.setObjectName("selection_13")
        self.btn_10_1 = QtWidgets.QPushButton(self.panel_op10)
        self.btn_10_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_10_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op10.PNG);")
        self.btn_10_1.setText("")
        self.btn_10_1.setObjectName("btn_10_1")
        self.btn_10_2 = QtWidgets.QPushButton(self.panel_op10)
        self.btn_10_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_10_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op10_2.PNG);")
        self.btn_10_2.setText("")
        self.btn_10_2.setObjectName("btn_10_2")
        self.btn_10_3 = QtWidgets.QPushButton(self.panel_op10)
        self.btn_10_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_10_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op10_3.PNG);")
        self.btn_10_3.setText("")
        self.btn_10_3.setObjectName("btn_10_3")
        self.btn_10_4 = QtWidgets.QPushButton(self.panel_op10)
        self.btn_10_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_10_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op10_4.PNG);")
        self.btn_10_4.setText("")
        self.btn_10_4.setObjectName("btn_10_4")
        self.panel_op11 = QtWidgets.QFrame(self.centralwidget)
        self.panel_op11.setEnabled(True)
        self.panel_op11.setGeometry(QtCore.QRect(600, 70, 185, 300))
        self.panel_op11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.panel_op11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.panel_op11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panel_op11.setObjectName("panel_op11")
        self.selection_14 = QtWidgets.QLabel(self.panel_op11)
        self.selection_14.setGeometry(QtCore.QRect(1, 1, 183, 298))
        self.selection_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selection_14.setText("")
        self.selection_14.setObjectName("selection_14")
        self.btn_11_1 = QtWidgets.QPushButton(self.panel_op11)
        self.btn_11_1.setGeometry(QtCore.QRect(5, 5, 85, 50))
        self.btn_11_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op11.PNG);")
        self.btn_11_1.setText("")
        self.btn_11_1.setObjectName("btn_11_1")
        self.btn_11_2 = QtWidgets.QPushButton(self.panel_op11)
        self.btn_11_2.setGeometry(QtCore.QRect(95, 5, 85, 50))
        self.btn_11_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op11_2.PNG);")
        self.btn_11_2.setText("")
        self.btn_11_2.setObjectName("btn_11_2")
        self.btn_11_3 = QtWidgets.QPushButton(self.panel_op11)
        self.btn_11_3.setGeometry(QtCore.QRect(5, 60, 85, 50))
        self.btn_11_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op11_3.PNG);")
        self.btn_11_3.setText("")
        self.btn_11_3.setObjectName("btn_11_3")
        self.btn_11_4 = QtWidgets.QPushButton(self.panel_op11)
        self.btn_11_4.setGeometry(QtCore.QRect(95, 60, 85, 50))
        self.btn_11_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op11_4.PNG);")
        self.btn_11_4.setText("")
        self.btn_11_4.setObjectName("btn_11_4")
        self.btn_11_5 = QtWidgets.QPushButton(self.panel_op11)
        self.btn_11_5.setGeometry(QtCore.QRect(5, 120, 85, 50))
        self.btn_11_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(:/op/op11_5.PNG);")
        self.btn_11_5.setText("")
        self.btn_11_5.setObjectName("btn_11_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_op1.clicked.connect(self.panel_op1.raise)
        self.btn_op2.clicked.connect(self.panel_op2.raise)
        self.btn_op3.clicked.connect(self.panel_op3.raise)
        self.btn_op4.clicked.connect(self.panel_op4.raise)
        self.btn_op5.clicked.connect(self.panel_op5.raise)
        self.btn_op6.clicked.connect(self.panel_op6.raise)
        self.btn_op7.clicked.connect(self.panel_op7.raise)
        self.btn_op8.clicked.connect(self.panel_op8.raise)
        self.btn_op9.clicked.connect(self.panel_op9.raise)
        self.btn_op10.clicked.connect(self.panel_op10.raise)
        self.btn_op11.clicked.connect(self.panel_op11.raise)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "MathTeacher"))

import back_arrow_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

